---
title: Governance
---

## Scientific committee

The IUCN Global Ecosystem Typology (GET) was developed by Red List of Ecosystems (RLE) Thematic Group of the Commission on Ecosystem Management (CEM) and led to IUCN Publication, dedicated web app (<https://global-ecosystems.org>), and scientific articles.

IUCN is committed to maintaining the Global Ecosystem Typology as the global knowledge base on ecosystems continually grows. 

The ***Global Ecosystem Typology Scientific Committee (GET-SC)*** was established in 2024 to advise on scientific and technical aspects of the maintenance and update of the GET to ensure high standards of scientific excellence and its fitness for purpose across diverse applications.

Updates may include revisions to ecosystem descriptions or maps, how lower levels of the typology will be populated and, where essential, changes to upper levels of classification, given the need for overall stability of the framework to serve its purposes effectively. 

The Committee will comprise a small core group of global experts and young professionals, with provisions for invited topic experts, where required to resolve specific update issues. 

The committee meets virtually at least twice per year.

Terms of reference for the committee are available upon request.

### Members of the GET-SC

- Chair: Prof. David Keith
- Members: 
    - Marcos Valderrabano
    - Walter Dodds
    - Janet Franklin
    - Paul Giller
    - Caroline Lehmann
    - Kerry Sink
    - Eva Ramirez-Llodra
    - Anisha Dayam
    - Mishal Gudka
    - Roxane Francis
    - Sylvia Hay
    - José R. Ferrer-Paris

### Meeting schedule

- 30 October 2024
- 23 June 2025
- 8 September 2025

## GET Data Hub

The GET data hub is currently responsible for:

- maintenance of GET digital assets including web-app, internal database and repositories,
- implementation of the recommendations 

Members of the GET data hub:

- General factotum: José R. Ferrer-Paris